### ISSUE TITLE
Installation failed: No package 'dbus-1' found

### ISSUE THREAD

**Issue by wintermute42** [erpalma/lenovo-throttling-fix#5]
First of all, thank you for this fix :-)

Unfortunately the installation according to readme failed on my system:
`
configure: error: Package requirements (dbus-1 >= 1.6) were not met:
    
    No package 'dbus-1' found
    
    Consider adjusting the PKG_CONFIG_PATH environment variable if you
    installed software in a non-standard prefix.
    
    Alternatively, you may set the environment variables DBUS_CFLAGS
    and DBUS_LIBS to avoid the need to call pkg-config.
    See the pkg-config man page for more details.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-va9i90_i/dbus-python/setup.py", line 106, in <module>
        'build_ext': BuildExt,
      File "/opt/lenovo_fix/venv/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/opt/lenovo_fix/venv/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.6/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-va9i90_i/dbus-python/setup.py", line 62, in run
        cwd=builddir)
      File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/tmp/pip-install-va9i90_i/dbus-python/configure', '--disable-maintainer-mode', 'PYTHON=/opt/lenovo_fix/venv/bin/python3', '--prefix=/tmp/pip-install-va9i90_i/dbus-python/build/temp.linux-x86_64-3.6/prefix']' returned non-zero exit status 1.
    `
`
    ----------------------------------------
Command "/opt/lenovo_fix/venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-va9i90_i/dbus-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-jp1pmzfa/install-record.txt --single-version-externally-managed --compile --install-headers /opt/lenovo_fix/venv/include/site/python3.6/dbus-python" failed with error code 1 in /tmp/pip-install-va9i90_i/dbus-python/
`
Can you help me?

**Comment by erpalma** [comment]
Which distro are you running?

**Comment by wintermute42** [comment]
Ubuntu 18.04

Francesco Palmarini <notifications@github.com> schrieb am Di., 8. Mai 2018,
10:54:

**Comment by erpalma** [comment]
You are right, I've tested the install script on a clean 18.04 VM. Try to install these missing dependencies:

`sudo apt install git virtualenv build-essential python3-dev libdbus-glib-1-dev libgirepository1.0-dev`

I've updated the README.

**Comment by wintermute42** [comment]
Thank you for your help. I installed the missing dependencies and I think it brought me one step closer. Unfortunately, now I get a different error. Seems I'm still missing something (cairo?). Can you maybe give me a hint how to solve this?
`
  Running setup.py install for dbus-python ... done
  Running setup.py install for pycairo ... error
    Complete output from command /opt/lenovo_fix/venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-vlttu6oc/pycairo/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-7x1506lg/install-record.txt --single-version-externally-managed --compile --install-headers /opt/lenovo_fix/venv/include/site/python3.6/pycairo:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/cairo
    copying cairo/__init__.py -> build/lib.linux-x86_64-3.6/cairo
    copying cairo/__init__.pyi -> build/lib.linux-x86_64-3.6/cairo
    copying cairo/py.typed -> build/lib.linux-x86_64-3.6/cairo
    running build_ext
    Package cairo was not found in the pkg-config search path.
    Perhaps you should add the directory containing `cairo.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'cairo' found
    Command '['pkg-config', '--print-errors', '--exists', 'cairo >= 1.13.1']' returned non-zero exit status 1.
    
    ----------------------------------------
Command "/opt/lenovo_fix/venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-vlttu6oc/pycairo/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-7x1506lg/install-record.txt --single-version-externally-managed --compile --install-headers /opt/lenovo_fix/venv/include/site/python3.6/pycairo" failed with error code 1 in /tmp/pip-install-vlttu6oc/pycairo/
`

**Comment by erpalma** [comment]
I think I forgot `libcairo2-dev`

**Comment by andriyor** [comment]
In my case, installing dbus with brew helped `brew install dbus`

**Comment by cnrmck** [comment]
This worked for me on Ubuntu 16.04.1 LTS

```bash
sudo apt install git virtualenv build-essential python3-dev libdbus-glib-1-dev libgirepository1.0-dev libcairo2-dev
pip3 install dbus-python
```
